name: Update Milestone

on:
  pull_request:
    types: [opened, reopened]

jobs:
  update:
    runs-on: ubuntu-latest
    name: update-milestone

    steps:
      - uses: andrefcdias/add-to-milestone
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: "+([0-9]).+([0-9]).+([0-9])"
          use-expression: true

