name: Set Milestone

on:
  pull_request:
    types: [opened, reopened]

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: set-milestone
        uses: andrefcdias/add-to-milestone
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: "+([0-9]).+([0-9]).+([0-9])"
          use-expression: true

